version: '3.8'

services:
  db-cliente:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: db-postgres
      POSTGRES_PASSWORD: db-postgres
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
##docker exec -it CONTAINER_NAME psql -U DB_USER -d DB_NAME