version: '1.0'

services:
  db-cliente:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: db-postgres
      POSTGRES_PASSWORD: db-postgres
      POSTGRES_DB: db-postgress
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: